version: "3.9"

# Docker compose for running a local {{cookiecutter.package_name}} instance
services:

  {{cookiecutter.package_name}}:
    image: "{{cookiecutter.package_name}}:0.1.0"
    build: "."
    container_name: "{{cookiecutter.package_name}}"
    env_file:
      - "local/override-docker.env"
    ports:
      - "2000:2000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500M"
        reservations:
          cpus: "1.0"
          memory: "500M"
    links:
      - "postgresql:postgresql"
    depends_on:
      - "postgresql"

  postgresql:
    image: "docker.io/bitnami/postgresql:latest"
    container_name: "{{cookiecutter.package_name}}_database"
    platform: "linux/amd64"
    environment:
      - "POSTGRESQL_USERNAME=local_user"
      - "POSTGRESQL_PASSWORD=very-secure-password"
      - "POSTGRESQL_DATABASE=api_db"
      - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "5432:5432"
    volumes:
      - "./local/db_data:/bitnami/postgresql/data/"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1000M"
        reservations:
          cpus: "2.0"
          memory: "1000M"