
# Docker compose for running a local {{cookiecutter.friendly_name}} instance
services:

  {{cookiecutter.package_name}}:
    image: "{{cookiecutter.package_name}}:local"
    build:
      context: "."
      target: "api"
      args:
        ARG_PROJECT_VERSION: "docker"
        ARG_POETRY_VERSION: "2.4.1"
        ARG_PYTHON_VERSION: "3.14"
    container_name: "{{cookiecutter.package_name}}"
    env_file:
      - "local/override-docker.env"
    ports:
      - "2000:2000"
    healthcheck:
      test: ["CMD", "bash", "scripts/run_health_check.sh"]
      interval: "10s"
      timeout: "5s"
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2048M"
        reservations:
          cpus: "2"
          memory: "2048M"
    links:
      - "{{cookiecutter.package_name}}_postgres:{{cookiecutter.package_name}}_postgres"
      - "{{cookiecutter.package_name}}_redis:{{cookiecutter.package_name}}_redis"
    depends_on:
      {{cookiecutter.package_name}}_postgres:
        condition: "service_healthy"
      {{cookiecutter.package_name}}_redis:
        condition: "service_healthy"
      {{cookiecutter.package_name}}_postgres_migration:
        condition: "service_completed_successfully"

  {{cookiecutter.package_name}}_unit_tests:
    image: "{{cookiecutter.package_name}}_unit_tests:local"
    build:
      context: "."
      target: "api_unit_tests"
      args:
        ARG_PROJECT_VERSION: "docker"
        ARG_POETRY_VERSION: "2.4.1"
        ARG_PYTHON_VERSION: "3.14"
    container_name: "{{cookiecutter.package_name}}_unit_tests"

  {{cookiecutter.package_name}}_integration_tests:
    image: "{{cookiecutter.package_name}}_integration_tests:local"
    build:
      context: "."
      target: "api_integration_tests"
      args:
        ARG_PROJECT_VERSION: "docker"
        ARG_POETRY_VERSION: "2.4.1"
        ARG_PYTHON_VERSION: "3.14"
    container_name: "{{cookiecutter.package_name}}_integration_tests"
    env_file:
      - "local/override-docker-integration.env"
    depends_on:
      {{cookiecutter.package_name}}:
        condition: "service_healthy"

  {{cookiecutter.package_name}}_postgres_migration:
    image: "{{cookiecutter.package_name}}_postgres_migration:local"
    build:
      context: "."
      target: "api_db_migration"
      args:
        ARG_PROJECT_VERSION: "docker"
        ARG_POETRY_VERSION: "2.4.1"
        ARG_PYTHON_VERSION: "3.14"
    container_name: "{{cookiecutter.package_name}}_postgres_migration"
    env_file:
      - "local/override-docker.env"
    links:
      - "{{cookiecutter.package_name}}_postgres:{{cookiecutter.package_name}}_postgres"
    depends_on:
      {{cookiecutter.package_name}}_postgres:
        condition: "service_healthy"

  {{cookiecutter.package_name}}_postgres:
    image: "docker.io/postgres:alpine3.23"
    container_name: "{{cookiecutter.package_name}}_database"
    environment:
      - "POSTGRES_USER=local_user"
      - "POSTGRES_PASSWORD=very-secure-password"
      - "POSTGRES_DB={{cookiecutter.package_name}}"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d {{cookiecutter.package_name}} -h 127.0.0.1 -p 5432"]
      interval: "10s"
      timeout: "5s"
      retries: 5
    volumes:
      - "./local/db_data/{{cookiecutter.package_name}}:/var/lib/postgresql"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "3840M"
        reservations:
          cpus: "1.0"
          memory: "3840M"

  {{cookiecutter.package_name}}_redis:
    image: "docker.io/redis:alpine3.23"
    container_name: "{{cookiecutter.package_name}}_redis"
    command: "redis-server --requirepass very-secure-password"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: "10s"
      timeout: "5s"
      retries: 5
    volumes:
      - "./local/redis_data:/data"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100M"
        reservations:
          cpus: "0.5"
          memory: "100M"
