version: "3.9"

# Docker compose for running a local {{cookiecutter.friendly_name}} instance
services:

  {{cookiecutter.package_name}}:
    image: "{{cookiecutter.package_name}}:0.1.0"
    build:
      context: "."
      target: "api"
      args:
        POETRY_VERSION: "1.7.1"
        PYTHON_VERSION: "3.12"
    container_name: "{{cookiecutter.package_name}}"
    env_file:
      - "local/override-docker.env"
    ports:
      - "2000:2000"
    healthcheck:
      test: ["CMD", "bash", "scripts/run_health_check.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500M"
        reservations:
          cpus: "1.0"
          memory: "500M"
    links:
      - "{{cookiecutter.package_name}}_postgres:{{cookiecutter.package_name}}_postgres"
      - "{{cookiecutter.package_name}}_redis:{{cookiecutter.package_name}}_redis"
    depends_on:
      - "{{cookiecutter.package_name}}_postgres"
      - "{{cookiecutter.package_name}}_redis"

  {{cookiecutter.package_name}}_unit_tests:
    image: "{{cookiecutter.package_name}}_unit_tests:0.1.0"
    build:
      context: "."
      target: "api_unit_tests"
      args:
        POETRY_VERSION: "1.7.1"
        PYTHON_VERSION: "3.12"
    container_name: "{{cookiecutter.package_name}}_unit_tests"

  {{cookiecutter.package_name}}_integration_tests:
    image: "{{cookiecutter.package_name}}_integration_tests:0.1.0"
    build:
      context: "."
      target: "api_integration_tests"
      args:
        POETRY_VERSION: "1.7.1"
        PYTHON_VERSION: "3.12"
    container_name: "{{cookiecutter.package_name}}_integration_tests"
    env_file:
      - "local/override-docker-integration.env"
    depends_on:
      {{cookiecutter.package_name}}:
        condition: "service_healthy"

  {{cookiecutter.package_name}}_postgres:
    image: "docker.io/bitnami/postgresql:latest"
    container_name: "{{cookiecutter.package_name}}_database"
    platform: "linux/amd64"
    environment:
      - "POSTGRESQL_USERNAME=local_user"
      - "POSTGRESQL_PASSWORD=very-secure-password"
      - "POSTGRESQL_DATABASE={{cookiecutter.package_name}}"
    ports:
      - "5432:5432"
    volumes:
      - "./local/db_data:/bitnami/postgresql"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1000M"
        reservations:
          cpus: "2.0"
          memory: "1000M"

  {{cookiecutter.package_name}}_redis:
    image: "docker.io/bitnami/redis:latest"
    container_name: "{{cookiecutter.package_name}}_redis"
    platform: "linux/amd64"
    environment:
      - "REDIS_PASSWORD=very-secure-password"
    ports:
      - "6379:6379"
    volumes:
      - "./local/redis_data:/bitnami/redis"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100M"
        reservations:
          cpus: "0.5"
          memory: "100M"
