[tool.poetry]
name = "{{cookiecutter.project_name}}"
description = "{{cookiecutter.project_description}}"
version = "0.1.0"
license = "MIT"
authors = {{cookiecutter.project_authors}}

[tool.poetry.dependencies]
asyncpg = "^0.28.0"
concurrent-log-handler = "^0.9.24"
fastapi = "^0.103.2"
greenlet = "^3.0.0"
gunicorn = "^21.2.0"
httptools = "^0.6.1"
httpx = {extras = ["h2"], version = "^0.25.0"}
prometheus-fastapi-instrumentator = "^6.1.0"
psycopg2-binary = "^2.9.8"
pydantic = {extras = ["email"], version = "^2.4.2"}
pydantic-settings = "^2.0.3"
python = "^3.11"
python-dotenv = "^1.0.0"
python-jose = "^3.3.0"
python-multipart = "^0.0.6"
redis = {extras = ["hiredis"], version = "^5.0.1"}
requests = "^2.31.0"
SQLAlchemy = "^2.0.21"
tenacity = "^8.2.3"
types-redis = "^4.6.0.7"
uvicorn = "^0.23.2"
uvloop = "^0.18.0"

[tool.poetry.group.dev.dependencies]
alembic = "^1.12.0"
pre-commit = "^3.4.0"

[tool.poetry.group.test.dependencies]
locust = "^2.16.1"
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py311"]
include = "\\.pyi?$"
exclude = """
/(
     \\.eggs
   | \\.git
   | \\.hg
   | \\.mypy_cache
   | \\.tox
   | \\.venv
   | _build
   | buck-out
   | build
   | dist
 )/
"""

[tool.isort]
known_first_party = ["{{cookiecutter.package_name}}", "migrations", "scripts", "tests"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
force_grid_wrap = 0
line_length = 100
multi_line_output = 3
ensure_newline_before_comments = "True"
include_trailing_comma = "True"
use_parentheses = "True"
