[tool.poetry]
name = "{{cookiecutter.project_name}}"
description = "{{cookiecutter.project_description}}"
version = "0.1.0"
license = "MIT"
authors = {{cookiecutter.project_authors}}

[tool.poetry.dependencies]
alembic = "^1.9.2"
asyncpg = "^0.27.0"
fastapi = "^0.90.0"
greenlet = "^2.0.2"
gunicorn = "^20.1.0"
httpx = {extras = ["h2"], version = "^0.23.3"}
prometheus-fastapi-instrumentator = "^5.9.1"
psycopg2-binary = "^2.9.5"
pydantic = {extras = ["email"], version = "^1.10.4"}
python = "^3.11"
python-dotenv = "^0.21.1"
python-jose = "^3.3.0"
python-multipart = "^0.0.5"
redis = "^4.5.1"
requests = "^2.28.2"
SQLAlchemy = "^2.0.1"
tenacity = "^8.1.0"
types-redis = "^4.5.1.0"
uvicorn = "^0.20.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.4"

[tool.poetry.group.test.dependencies]
locust = "^2.14.2"
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
requests = "^2.28.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py310"]
include = "\\.pyi?$"
exclude = """
/(
     \\.eggs
   | \\.git
   | \\.hg
   | \\.mypy_cache
   | \\.tox
   | \\.venv
   | _build
   | buck-out
   | build
   | dist
 )/
"""

[tool.isort]
known_first_party = ["{{cookiecutter.package_name}}", "migrations", "scripts", "tests"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
force_grid_wrap = 0
line_length = 100
multi_line_output = 3
ensure_newline_before_comments = "True"
include_trailing_comma = "True"
use_parentheses = "True"