[tool.poetry]
name = "{{cookiecutter.project_name}}"
description = "{{cookiecutter.project_description}}"
version = "0.1.0"
license = "MIT"
authors = {{cookiecutter.project_authors}}

[tool.poetry.dependencies]
alembic = "^1.11.1"
asyncpg = "^0.28.0"
fastapi = "^0.100.0"
greenlet = "^2.0.2"
gunicorn = "^21.2.0"
httptools = "^0.6.0"
httpx = {extras = ["h2"], version = "^0.24.1"}
prometheus-fastapi-instrumentator = "^6.1.0"
psycopg2-binary = "^2.9.5"
pydantic = {extras = ["email"], version = "^2.1.1"}
pydantic-settings = "^2.0.2"
python = "^3.11"
python-dotenv = "^1.0.0"
python-jose = "^3.3.0"
python-multipart = "^0.0.6"
redis = {extras = ["hiredis"], version = "^4.6.0"}
requests = "^2.31.0"
SQLAlchemy = "^2.0.14"
tenacity = "^8.2.2"
types-redis = "^4.6.0.3"
uvicorn = "^0.23.1"
uvloop = "^0.17.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"

[tool.poetry.group.test.dependencies]
locust = "^2.15.0"
pytest = "^7.3.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
requests = "^2.28.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py311"]
include = "\\.pyi?$"
exclude = """
/(
     \\.eggs
   | \\.git
   | \\.hg
   | \\.mypy_cache
   | \\.tox
   | \\.venv
   | _build
   | buck-out
   | build
   | dist
 )/
"""

[tool.isort]
known_first_party = ["{{cookiecutter.package_name}}", "migrations", "scripts", "tests"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
force_grid_wrap = 0
line_length = 100
multi_line_output = 3
ensure_newline_before_comments = "True"
include_trailing_comma = "True"
use_parentheses = "True"
